---
title: "01 - load"
format: html
editor: visual
---

```{r}
library(readr)
```

Download files from websource

```{r}
#| eval: !file.exists("data/TCGA-OV.star_fpkm.tsv.gz")
#| message: true
#| warning: false

dir.create("../data/_raw", recursive = TRUE, showWarnings = FALSE)

urls <- c(
  "https://gdc-hub.s3.us-east-1.amazonaws.com/download/TCGA-OV.clinical.tsv.gz",
  "https://gdc-hub.s3.us-east-1.amazonaws.com/download/TCGA-OV.star_fpkm.tsv.gz"
)

files <- file.path("../data/_raw", basename(urls))
options(timeout = 600) # To load heavy file

for (i in seq_along(urls)) {
  if (!file.exists(files[i])) {
    message("Downloading ", basename(urls[i]), " ...")
    download.file(
      urls[i], 
      files[i], 
      mode = "wb",
      method = "curl" # For large files
      )
  } else {
    message(basename(urls[i]), " already exists, skipping.")
  }
}

```

Load data

```{r}
gen_exp <- read_tsv("../data/_raw/TCGA-OV.star_fpkm.tsv.gz")
phenotype <- read_tsv("../data/_raw/TCGA-OV.clinical.tsv.gz")

saveRDS(phenotype, "../data/phenotype.rds")
saveRDS(gen_exp, "../data/gen_exp.rds")
```
