{
  "hash": "d1049f5e837c93081d7a7d734e445293",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"02 - clean\"\nformat: html\neditor: visual\nexecute:\n  cache: false\n---\n\n# Load libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"tidyverse\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: le package 'tidyverse' a été compilé avec la version R 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: le package 'ggplot2' a été compilé avec la version R 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: le package 'readr' a été compilé avec la version R 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: le package 'purrr' a été compilé avec la version R 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: le package 'stringr' a été compilé avec la version R 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: le package 'forcats' a été compilé avec la version R 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.6\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.1     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.2.0     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(\"dplyr\")\n```\n:::\n\n\n# Clean gene table\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngen_exp <- readRDS(\"../data/gen_exp.rds\")\ndim(gen_exp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 60660   430\n```\n\n\n:::\n\n```{.r .cell-code}\ngen_exp |> \n  slice_sample(n = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 430\n   Ensembl_ID        `TCGA-24-1104-01A` `TCGA-25-1320-01A` `TCGA-24-1850-01A`\n   <chr>                          <dbl>              <dbl>              <dbl>\n 1 ENSG00000273942.1             0                  0                  0     \n 2 ENSG00000199862.1             0                  0                  0     \n 3 ENSG00000271086.7             0.0380             0.0380             0.0596\n 4 ENSG00000249460.2             0                  0                  0.287 \n 5 ENSG00000269420.5             0                  0.0467             0     \n 6 ENSG00000254329.1             0                  0                  0     \n 7 ENSG00000202044.1             0                  0                  0     \n 8 ENSG00000137441.8             0.278              0.0682             0.253 \n 9 ENSG00000287325.1             0.0272             0                  0.0487\n10 ENSG00000248767.2             0                  0.0189             0     \n# ℹ 426 more variables: `TCGA-61-2101-01A` <dbl>, `TCGA-23-1111-01A` <dbl>,\n#   `TCGA-25-2396-01A` <dbl>, `TCGA-30-1714-01A` <dbl>,\n#   `TCGA-04-1347-01A` <dbl>, `TCGA-59-2351-01A` <dbl>,\n#   `TCGA-09-1659-01B` <dbl>, `TCGA-24-1431-01A` <dbl>,\n#   `TCGA-31-1951-01A` <dbl>, `TCGA-29-1769-01A` <dbl>,\n#   `TCGA-13-0916-01A` <dbl>, `TCGA-61-1721-01A` <dbl>,\n#   `TCGA-61-2008-02A` <dbl>, `TCGA-20-1687-01A` <dbl>, …\n```\n\n\n:::\n:::\n\n\nWe have 60600 observations (rows) and 430 variables (columns). The rows are the different genes and the columns are the samples. We have 60600 genes (that is too much) and we can see that some of them are 0 for all the samples. So we want to delete all the gene with no expression for each sample.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngen_exp_clean <- gen_exp |>\n  filter(rowSums(across(-Ensembl_ID)) != 0)\ndim(gen_exp_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 57825   430\n```\n\n\n:::\n:::\n\n\nWe steel have too much genes (57825) so we want to see which genes are unuseful\n\nWe calculate the sum of all the gene expression for each gene\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngen_exp_clean <- gen_exp_clean |>\n  mutate(sum_gene_exp = rowSums(across(-Ensembl_ID))) |>\n  relocate(sum_gene_exp, .after = Ensembl_ID) |>\n  arrange(sum_gene_exp)\ngen_exp_clean |> \n  slice_sample(n = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 431\n   Ensembl_ID         sum_gene_exp `TCGA-24-1104-01A` `TCGA-25-1320-01A`\n   <chr>                     <dbl>              <dbl>              <dbl>\n 1 ENSG00000286383.1       215.                0                  0.704 \n 2 ENSG00000148082.10       84.1               0.0760             0.133 \n 3 ENSG00000234906.11       28.0               0.118              0.141 \n 4 ENSG00000120437.9      1070.                2.96               2.33  \n 5 ENSG00000236400.1         0.306             0                  0     \n 6 ENSG00000240729.1       131.                0.203              0.346 \n 7 ENSG00000259282.5         1.50              0                  0     \n 8 ENSG00000258689.1        72.2               0.0838             0.0996\n 9 ENSG00000280362.1        73.9               0.208              0.0915\n10 ENSG00000242793.1         0.221             0                  0     \n# ℹ 427 more variables: `TCGA-24-1850-01A` <dbl>, `TCGA-61-2101-01A` <dbl>,\n#   `TCGA-23-1111-01A` <dbl>, `TCGA-25-2396-01A` <dbl>,\n#   `TCGA-30-1714-01A` <dbl>, `TCGA-04-1347-01A` <dbl>,\n#   `TCGA-59-2351-01A` <dbl>, `TCGA-09-1659-01B` <dbl>,\n#   `TCGA-24-1431-01A` <dbl>, `TCGA-31-1951-01A` <dbl>,\n#   `TCGA-29-1769-01A` <dbl>, `TCGA-13-0916-01A` <dbl>,\n#   `TCGA-61-1721-01A` <dbl>, `TCGA-61-2008-02A` <dbl>, …\n```\n\n\n:::\n:::\n\n\nNow we want to visualise this new varaible to know what treshold we are going to use to select the relevant genes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gen_exp_clean, aes(x = Ensembl_ID, y = sum_gene_exp)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](02_clean_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(gen_exp_clean, aes(x = sum_gene_exp)) +\n  geom_histogram(binwidth = 100)\n```\n\n::: {.cell-output-display}\n![](02_clean_files/figure-html/unnamed-chunk-5-2.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(gen_exp_clean, aes(y = sum_gene_exp)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](02_clean_files/figure-html/unnamed-chunk-5-3.png){width=672}\n:::\n:::\n\n\nWe can see that a lot of genes have the sum around 0 (with the boxplot). In the histogram, the binwidth is 100 and 4 bars are higher than the others and correspond to irelevant genes. So we can choose a treshold of 400. There are 431 samples so a threshold of 400 means that in average, apromimativelly all the genes expressions are higher than 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngen_exp_clean <- gen_exp_clean |>\n  filter(sum_gene_exp > 400)\ndim(gen_exp_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14157   431\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gen_exp_clean, aes(x = sum_gene_exp)) +\n  geom_histogram(binwidth = 100)\n```\n\n::: {.cell-output-display}\n![](02_clean_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nNow, we have 14157 genes which is more appropriate for our case.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsaveRDS(gen_exp_clean, \"../data/gen_exp_clean.rds\")\n```\n:::\n\n\n# Cleaning Phenotype table\n\n## Loading table\n\nWe start by loading the \"phenotype\" table, with the raw clinical data. The slice_sample allows to see 20 random samples and start evaluating which variables (columns) will be useful\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphenotype <- readRDS(\"../data/phenotype.rds\")\nphenotype |> \n  slice_sample(n = 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20 × 84\n   sample           id            disease_type case_id submitter_id primary_site\n   <chr>            <chr>         <chr>        <chr>   <chr>        <chr>       \n 1 TCGA-24-2026-01A 2517ca7a-605… Cystic, Muc… 2517ca… TCGA-24-2026 Ovary       \n 2 TCGA-01-0642-11A 55afc59f-36a… Not Reported 55afc5… TCGA-01-0642 Ovary       \n 3 TCGA-13-1505-01A 914f84bf-578… Cystic, Muc… 914f84… TCGA-13-1505 Ovary       \n 4 TCGA-24-2019-01A bbad2efe-e9c… Cystic, Muc… bbad2e… TCGA-24-2019 Ovary       \n 5 TCGA-09-0369-01A 1d9893c8-0de… Cystic, Muc… 1d9893… TCGA-09-0369 Ovary       \n 6 TCGA-5X-AA5U-01A bc84c5c5-178… Cystic, Muc… bc84c5… TCGA-5X-AA5U Ovary       \n 7 TCGA-13-0890-01A ee0a4a13-613… Cystic, Muc… ee0a4a… TCGA-13-0890 Ovary       \n 8 TCGA-24-1425-01A b120b701-c19… Cystic, Muc… b120b7… TCGA-24-1425 Ovary       \n 9 TCGA-25-1626-01A 662d77d1-1a4… Cystic, Muc… 662d77… TCGA-25-1626 Ovary       \n10 TCGA-61-2018-01A 13d6c31a-689… Cystic, Muc… 13d6c3… TCGA-61-2018 Ovary       \n11 TCGA-61-1728-01A 07fbdb3c-833… Cystic, Muc… 07fbdb… TCGA-61-1728 Ovary       \n12 TCGA-13-1817-02A 8ae56ffc-960… Cystic, Muc… 8ae56f… TCGA-13-1817 Ovary       \n13 TCGA-01-0633-11A dde3c31f-51c… Not Reported dde3c3… TCGA-01-0633 Ovary       \n14 TCGA-61-1736-01B 0a2d29de-869… Cystic, Muc… 0a2d29… TCGA-61-1736 Ovary       \n15 TCGA-13-2066-01A bcb87812-94e… Cystic, Muc… bcb878… TCGA-13-2066 Ovary       \n16 TCGA-25-1323-01A 2ee36d9d-128… Cystic, Muc… 2ee36d… TCGA-25-1323 Ovary       \n17 TCGA-24-2295-01A 7bd1851f-7e2… Cystic, Muc… 7bd185… TCGA-24-2295 Ovary       \n18 TCGA-61-1738-01A 72c40fba-f50… Cystic, Muc… 72c40f… TCGA-61-1738 Ovary       \n19 TCGA-30-1853-01A 5d603bba-62e… Cystic, Muc… 5d603b… TCGA-30-1853 Ovary       \n20 TCGA-24-2293-01A bdd792e7-d75… Cystic, Muc… bdd792… TCGA-24-2293 Ovary       \n# ℹ 78 more variables: alcohol_history.exposures <chr>, race.demographic <chr>,\n#   gender.demographic <chr>, ethnicity.demographic <chr>,\n#   vital_status.demographic <chr>, age_at_index.demographic <dbl>,\n#   days_to_birth.demographic <dbl>, year_of_birth.demographic <dbl>,\n#   days_to_death.demographic <dbl>, year_of_death.demographic <dbl>,\n#   primary_site.project <chr>, project_id.project <chr>,\n#   disease_type.project <chr>, name.project <chr>, …\n```\n\n\n:::\n:::\n\n\n### Removal of variables\n\nWe start by removing some unuseful variables, such as:\n\n-   \"id\", \"case_id\", \"tissue_source_site_id.tissue_source_site\", \"entity_id.annotations\", \"annotation_id.annotations\" and other:\\\n    They are long lists of seemingly random characters, useful for identification of the sample but not for analysis, as we have no information on their meaning.\\\n    We'll use \"sample\" as identification.\n\n-   \"submitter_id\", \"entity_submitter_id.annotations\" :\\\n    They are the same as \"sample\" without the last 3 characters. This is repetitive and untidy.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Shows how some variables repeat the same information \nphenotype |> \n  select(c(sample, submitter_id)) |> \n  slice_sample(n = 20) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20 × 2\n   sample           submitter_id\n   <chr>            <chr>       \n 1 TCGA-42-2589-01A TCGA-42-2589\n 2 TCGA-04-1353-01A TCGA-04-1353\n 3 TCGA-25-1315-01A TCGA-25-1315\n 4 TCGA-13-0913-02A TCGA-13-0913\n 5 TCGA-13-0805-01A TCGA-13-0805\n 6 TCGA-10-0936-01A TCGA-10-0936\n 7 TCGA-04-1332-01A TCGA-04-1332\n 8 TCGA-13-1505-01A TCGA-13-1505\n 9 TCGA-24-0975-01A TCGA-24-0975\n10 TCGA-09-0366-01A TCGA-09-0366\n11 TCGA-29-2427-01A TCGA-29-2427\n12 TCGA-13-0916-01A TCGA-13-0916\n13 TCGA-13-2071-01A TCGA-13-2071\n14 TCGA-61-2097-01A TCGA-61-2097\n15 TCGA-24-1425-01A TCGA-24-1425\n16 TCGA-13-0730-01A TCGA-13-0730\n17 TCGA-61-1913-01A TCGA-61-1913\n18 TCGA-23-1113-01A TCGA-23-1113\n19 TCGA-24-1545-01A TCGA-24-1545\n20 TCGA-36-2551-01A TCGA-36-2551\n```\n\n\n:::\n\n```{.r .cell-code}\n# Shows identifier variables, no meaning for analysis \nphenotype |> \n  select(c(id, case_id)) |> \n  slice_sample(n = 20) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20 × 2\n   id                                   case_id                             \n   <chr>                                <chr>                               \n 1 99a61986-7b23-46b5-99a4-efba6bad3766 99a61986-7b23-46b5-99a4-efba6bad3766\n 2 4d71dd15-cd01-4dae-ad70-6dc325140207 4d71dd15-cd01-4dae-ad70-6dc325140207\n 3 f9793a4b-c0e7-4475-bf80-69543b7ee2f6 f9793a4b-c0e7-4475-bf80-69543b7ee2f6\n 4 cddbac56-2861-46a5-98a3-df32ab69d5da cddbac56-2861-46a5-98a3-df32ab69d5da\n 5 26558703-a659-43f2-86cb-0695989bc14e 26558703-a659-43f2-86cb-0695989bc14e\n 6 d8d13aa4-45d5-4e1a-a6cf-895bdf05e7b2 d8d13aa4-45d5-4e1a-a6cf-895bdf05e7b2\n 7 31b997dd-aaea-4003-a64d-11d3e19b0bbc 31b997dd-aaea-4003-a64d-11d3e19b0bbc\n 8 61feee94-3ac9-42fe-aaa3-dc6a3efe563c 61feee94-3ac9-42fe-aaa3-dc6a3efe563c\n 9 a36a4440-15ef-4837-904b-380a964d16f1 a36a4440-15ef-4837-904b-380a964d16f1\n10 7248cd60-be22-44bc-bc58-f644db0940a2 7248cd60-be22-44bc-bc58-f644db0940a2\n11 b0585c7a-7205-4dac-9d54-6da89674accb b0585c7a-7205-4dac-9d54-6da89674accb\n12 d73a0a33-e4e8-44bd-9580-2038ab06583a d73a0a33-e4e8-44bd-9580-2038ab06583a\n13 e3ea5137-76b8-4afc-9b80-ed74714e7172 e3ea5137-76b8-4afc-9b80-ed74714e7172\n14 0f530b3e-5b6d-4892-9ebd-9138d76fdca7 0f530b3e-5b6d-4892-9ebd-9138d76fdca7\n15 808eb134-9c7d-43bb-b86c-2f3259193954 808eb134-9c7d-43bb-b86c-2f3259193954\n16 644a88a7-dc56-468a-af5c-60278aab7642 644a88a7-dc56-468a-af5c-60278aab7642\n17 b25b3379-df8f-4900-9bce-0f8df50f549b b25b3379-df8f-4900-9bce-0f8df50f549b\n18 76cc2d21-eebc-4f09-9bc7-dbf7af0aafa8 76cc2d21-eebc-4f09-9bc7-dbf7af0aafa8\n19 cddbac56-2861-46a5-98a3-df32ab69d5da cddbac56-2861-46a5-98a3-df32ab69d5da\n20 8e107f4b-1912-4d3e-814a-b863e2d65ed7 8e107f4b-1912-4d3e-814a-b863e2d65ed7\n```\n\n\n:::\n\n```{.r .cell-code}\n# Remove these variables \nphenotype_clean <- phenotype |> \n  select(!c(id, \n            case_id, \n            submitter_id, \n            tissue_source_site_id.tissue_source_site, \n            entity_submitter_id.annotations, \n            entity_id.annotations, \n            annotation_id.annotations, \n            case_id.annotations, \n            treatment_id.treatments.diagnoses, \n            submitter_id.treatments.diagnoses, \n            sample_id.samples, \n            pathology_report_uuid.samples)\n         )\n```\n:::\n\n\n-   \"primary_site\", \"primary_site.project\", \"project_id.project\", ... : These columns contain the same observation for each row, and will not be useful for analysis either.\\\n    For example \"gender.demographic\" will always be \"female\", as we are studying ovarian cancer.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Shows variables with repeated observations \nphenotype_clean |> \n  select(c(primary_site, \n           name.program.project, \n           last_known_disease_status.diagnoses, \n           gender.demographic)) |> \n  slice_sample(n = 20) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20 × 4\n   primary_site name.program.project last_known_disease_sta…¹ gender.demographic\n   <chr>        <chr>                <chr>                    <chr>             \n 1 Ovary        TCGA                 not reported             female            \n 2 Ovary        TCGA                 not reported             female            \n 3 Ovary        TCGA                 not reported             female            \n 4 Ovary        TCGA                 not reported             female            \n 5 Ovary        TCGA                 not reported             female            \n 6 Ovary        TCGA                 not reported             female            \n 7 Ovary        TCGA                 not reported             female            \n 8 Ovary        TCGA                 not reported             female            \n 9 Ovary        TCGA                 not reported             female            \n10 Ovary        TCGA                 not reported             female            \n11 Ovary        TCGA                 not reported             female            \n12 Ovary        TCGA                 not reported             female            \n13 Ovary        TCGA                 not reported             female            \n14 Ovary        TCGA                 not reported             female            \n15 Ovary        TCGA                 not reported             female            \n16 Ovary        TCGA                 not reported             female            \n17 Ovary        TCGA                 not reported             female            \n18 Ovary        TCGA                 not reported             female            \n19 Ovary        TCGA                 not reported             female            \n20 Ovary        TCGA                 not reported             female            \n# ℹ abbreviated name: ¹​last_known_disease_status.diagnoses\n```\n\n\n:::\n\n```{.r .cell-code}\n# Remove these variables \nphenotype_clean <- phenotype_clean |> \n  select(!c(primary_site, \n            primary_site.project, \n            project_id.project, \n            disease_type.project, \n            name.project, \n            name.program.project, \n            project.tissue_source_site, \n            days_to_diagnosis.diagnoses, \n            last_known_disease_status.diagnoses, \n            tissue_or_organ_of_origin.diagnoses, \n            preservation_method.samples, \n            is_ffpe.samples, \n            gender.demographic)\n         )\n```\n:::\n\n\n-   \"entity_type.annotations\" , \"state.annotations\", ... : These are empty or always the same when not empty. Samples might come from different sources, which would explain irregular conventions. After careful reading of the table, we can say that the fact that some observations are left empty has no other meaning.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Shows variables with repeated or empty observations \nphenotype_clean |> \n  select(c(entity_type.annotations, \n           state.annotations, \n           status.annotations)) |> \n  slice_sample(n = 20) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20 × 3\n   entity_type.annotations state.annotations status.annotations\n   <chr>                   <chr>             <chr>             \n 1 <NA>                    <NA>              <NA>              \n 2 <NA>                    <NA>              <NA>              \n 3 <NA>                    <NA>              <NA>              \n 4 case                    released          Approved          \n 5 <NA>                    <NA>              <NA>              \n 6 <NA>                    <NA>              <NA>              \n 7 <NA>                    <NA>              <NA>              \n 8 <NA>                    <NA>              <NA>              \n 9 case                    released          Approved          \n10 <NA>                    <NA>              <NA>              \n11 <NA>                    <NA>              <NA>              \n12 case                    released          Approved          \n13 case                    released          Approved          \n14 <NA>                    <NA>              <NA>              \n15 <NA>                    <NA>              <NA>              \n16 <NA>                    <NA>              <NA>              \n17 case                    released          Approved          \n18 <NA>                    <NA>              <NA>              \n19 <NA>                    <NA>              <NA>              \n20 <NA>                    <NA>              <NA>              \n```\n\n\n:::\n\n```{.r .cell-code}\n# Remove these columns \nphenotype_clean <- phenotype_clean |> \n  select(!c(entity_type.annotations, \n            state.annotations, \n            status.annotations, \n            composition.samples, \n            days_to_sample_procurement.samples, \n            state.treatments.diagnoses,\n            tumor_grade.diagnoses,\n            progression_or_recurrence.diagnoses))\n```\n:::\n\n\nThe samples with a disease_type value other than \"Cystic, Mucinous and Serous Neoplasms\" miss a lot of other information (NA in other columns). We will not keep them as there are only 8 samples and will disturb analysis without providing new information. It now makes no sense to keep this column.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check for other disease types \nphenotype_clean |> \n  filter(disease_type != \"Cystic, Mucinous and Serous Neoplasms\") \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 51\n  sample           disease_type alcohol_history.exposures race.demographic\n  <chr>            <chr>        <chr>                     <chr>           \n1 TCGA-01-0633-11A Not Reported <NA>                      <NA>            \n2 TCGA-01-0628-11A Not Reported <NA>                      <NA>            \n3 TCGA-01-0630-11A Not Reported <NA>                      <NA>            \n4 TCGA-01-0631-11A Not Reported <NA>                      <NA>            \n5 TCGA-01-0637-11A Not Reported <NA>                      <NA>            \n6 TCGA-01-0636-11A Not Reported <NA>                      <NA>            \n7 TCGA-01-0642-11A Not Reported <NA>                      <NA>            \n8 TCGA-01-0639-11A Not Reported <NA>                      <NA>            \n# ℹ 47 more variables: ethnicity.demographic <chr>,\n#   vital_status.demographic <chr>, age_at_index.demographic <dbl>,\n#   days_to_birth.demographic <dbl>, year_of_birth.demographic <dbl>,\n#   days_to_death.demographic <dbl>, year_of_death.demographic <dbl>,\n#   code.tissue_source_site <chr>, name.tissue_source_site <chr>,\n#   bcr_id.tissue_source_site <chr>, notes.annotations <chr>,\n#   submitter_id.annotations <chr>, classification.annotations <chr>, …\n```\n\n\n:::\n\n```{.r .cell-code}\n# Remove samples with missing values \nphenotype_clean <- phenotype_clean |> \n  filter(disease_type == \"Cystic, Mucinous and Serous Neoplasms\")\n\n# Remove this column\nphenotype_clean <- phenotype_clean |> \n  select(!disease_type)\n```\n:::\n\n\nThe column prior_treatment.diagnoses is Not Reported or No for every samples except one Yes. This column will not be useful.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Show values other than \"Not Reported\" and \"No\" for prior_treatment.diagnoses\nphenotype_clean |> \n  filter(prior_treatment.diagnoses!=\"Not Reported\" &\n         prior_treatment.diagnoses != \"No\") |> \n  relocate(prior_treatment.diagnoses, .before = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 50\n  prior_treatment.diagnoses sample       alcohol_history.expo…¹ race.demographic\n  <chr>                     <chr>        <chr>                  <chr>           \n1 Yes                       TCGA-61-172… Not Reported           white           \n# ℹ abbreviated name: ¹​alcohol_history.exposures\n# ℹ 46 more variables: ethnicity.demographic <chr>,\n#   vital_status.demographic <chr>, age_at_index.demographic <dbl>,\n#   days_to_birth.demographic <dbl>, year_of_birth.demographic <dbl>,\n#   days_to_death.demographic <dbl>, year_of_death.demographic <dbl>,\n#   code.tissue_source_site <chr>, name.tissue_source_site <chr>,\n#   bcr_id.tissue_source_site <chr>, notes.annotations <chr>, …\n```\n\n\n:::\n:::\n\n\nSome variables don't always contain the same information on paper, but further analysis shows us that the observations are very similar. For example alcohol_history.exposures is \"Not reported\" or NA:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Show NAs in alcohol_history.exposures\nphenotype_clean |> \n  filter(is.na(alcohol_history.exposures)) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 11 × 50\n   sample          alcohol_history.expo…¹ race.demographic ethnicity.demographic\n   <chr>           <chr>                  <chr>            <chr>                \n 1 TCGA-36-2539-0… <NA>                   <NA>             <NA>                 \n 2 TCGA-72-4236-0… <NA>                   <NA>             <NA>                 \n 3 TCGA-72-4237-0… <NA>                   <NA>             <NA>                 \n 4 TCGA-72-4238-0… <NA>                   <NA>             <NA>                 \n 5 TCGA-72-4235-0… <NA>                   <NA>             <NA>                 \n 6 TCGA-72-4232-0… <NA>                   <NA>             <NA>                 \n 7 TCGA-72-4241-0… <NA>                   <NA>             <NA>                 \n 8 TCGA-72-4233-0… <NA>                   <NA>             <NA>                 \n 9 TCGA-72-4240-0… <NA>                   <NA>             <NA>                 \n10 TCGA-72-4231-0… <NA>                   <NA>             <NA>                 \n11 TCGA-72-4234-0… <NA>                   <NA>             <NA>                 \n# ℹ abbreviated name: ¹​alcohol_history.exposures\n# ℹ 46 more variables: vital_status.demographic <chr>,\n#   age_at_index.demographic <dbl>, days_to_birth.demographic <dbl>,\n#   year_of_birth.demographic <dbl>, days_to_death.demographic <dbl>,\n#   year_of_death.demographic <dbl>, code.tissue_source_site <chr>,\n#   name.tissue_source_site <chr>, bcr_id.tissue_source_site <chr>,\n#   notes.annotations <chr>, submitter_id.annotations <chr>, …\n```\n\n\n:::\n\n```{.r .cell-code}\n# Remove this column\nphenotype_clean <- phenotype_clean |> \n  select(!alcohol_history.exposures) \n```\n:::\n\n\nModification of the variable vital_status.demographic to a binary variable \"alive\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphenotype_clean <- phenotype_clean |> \n  mutate(vital_status.demographic = case_when(\n    vital_status.demographic == \"Alive\" ~ TRUE,\n    vital_status.demographic == \"Dead\" ~ FALSE,\n    TRUE ~ NA\n  ))|>\n  rename(alive=vital_status.demographic)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsaveRDS(phenotype_clean, \"../data/phenotype_clean.rds\")\n```\n:::\n\n",
    "supporting": [
      "02_clean_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}